#  _   _             _             _             
# | \ | | __ ___   _(_) __ _  __ _| |_ ___  _ __ 
# |  \| |/ _` \ \ / / |/ _` |/ _` | __/ _ \| '__|
# | |\  | (_| |\ V /| | (_| | (_| | || (_) | |   
# |_| \_|\__,_| \_/ |_|\__, |\__,_|\__\___/|_|   
#                      |___/                     
# Default config -------------------------------- 

selector = "> "

[theme.selected]
fg = [255, 255, 255]
# bg = ...

[theme.default]
fg = [40, 40, 40]
# bg = ...
